import { useStore } from '../store';
import { translations } from '../translations';
import { format } from 'date-fns';

export default function ReportTemplate() {
  const { predictionResult, formData, language } = useStore();
  const t = translations[language];

  if (!predictionResult) return null;

  return (
    <div id="print-report" className="hidden print:block bg-white text-black p-10 font-sans max-w-4xl mx-auto">
      <div className="border-b-2 border-emerald-600 pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-4xl font-bold text-zinc-900 mb-2">AgriPulse Smart Report</h1>
          <p className="text-zinc-600">Generated on {format(new Date(), 'MMMM d, yyyy')}</p>
        </div>
        <div className="text-right">
          <p className="font-bold text-zinc-800">Farm Location: <span className="text-emerald-600">{formData.location} Region</span></p>
          <p className="text-zinc-600">Crop Type: {formData.crop_type.toUpperCase()}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-8 mb-10">
        <div className="bg-zinc-100 p-6 rounded-lg">
          <h2 className="text-xl font-bold text-zinc-800 mb-4 border-b border-zinc-300 pb-2">Executive Summary</h2>
          <div className="space-y-4">
            <div>
              <p className="text-sm text-zinc-500 uppercase tracking-wide">Predicted Yield</p>
              <p className="text-3xl font-bold text-emerald-600">{predictionResult.yield_prediction} t/ha</p>
            </div>
            <div>
              <p className="text-sm text-zinc-500 uppercase tracking-wide">Estimated Profit</p>
              <p className="text-2xl font-bold text-zinc-800">${(predictionResult.yield_prediction * 5 * 250).toLocaleString()} <span className="text-sm font-normal text-zinc-500">(based on 5ha)</span></p>
            </div>
            <div>
              <p className="text-sm text-zinc-500 uppercase tracking-wide">Risk Assessment</p>
              <p className={`text-xl font-bold ${predictionResult.risk_level === 'High' ? 'text-red-600' : 'text-amber-500'}`}>{predictionResult.risk_level} Risk</p>
            </div>
          </div>
        </div>

        <div className="bg-zinc-100 p-6 rounded-lg">
          <h2 className="text-xl font-bold text-zinc-800 mb-4 border-b border-zinc-300 pb-2">Soil & Environment Data</h2>
          <div className="grid grid-cols-2 gap-y-4 gap-x-2">
            <div><span className="text-zinc-500 text-sm">Nitrogen (N):</span><br/><span className="font-bold">{formData.soil_n}</span></div>
            <div><span className="text-zinc-500 text-sm">Phosphorus (P):</span><br/><span className="font-bold">{formData.soil_p}</span></div>
            <div><span className="text-zinc-500 text-sm">Potassium (K):</span><br/><span className="font-bold">{formData.soil_k}</span></div>
            <div><span className="text-zinc-500 text-sm">Soil pH:</span><br/><span className="font-bold">{formData.soil_ph}</span></div>
            <div><span className="text-zinc-500 text-sm">Moisture:</span><br/><span className="font-bold">{formData.soil_moisture}%</span></div>
            <div><span className="text-zinc-500 text-sm">NDVI Index:</span><br/><span className="font-bold">{formData.ndvi}</span></div>
          </div>
        </div>
      </div>

      <div className="mb-10">
        <h2 className="text-2xl font-bold text-zinc-800 mb-4 border-b-2 border-emerald-600 pb-2">AI Action Plan & Recommendations</h2>
        <ul className="space-y-3">
          {predictionResult.recommendations?.map((rec, i) => (
            <li key={i} className="flex gap-3 items-start">
              <span className="text-emerald-600 font-bold mt-1">•</span>
              <span className="text-zinc-700 leading-relaxed">{rec}</span>
            </li>
          ))}
        </ul>
      </div>
      
      <div className="mt-16 pt-6 border-t border-zinc-300 text-center text-sm text-zinc-500">
        <p>This report was automatically generated by AgriPulse AI models.</p>
        <p>Model Confidence Score: {predictionResult.confidence_score}%</p>
      </div>
    </div>
  );
}
